DROP TABLE IF EXISTS ndc2010_listings;
DROP TABLE IF EXISTS ndc2012_listings;

DROP TABLE IF EXISTS ndc2010_packages;
DROP TABLE IF EXISTS ndc2012_packages;

DROP TABLE IF EXISTS ndc2018_packages;
DROP TABLE IF EXISTS ndc2025_packages;

DROP TABLE IF EXISTS ndc2018_product;
DROP TABLE IF EXISTS ndc2025_product;

VACUUM FULL ANALYZE;